# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Stefan Schimanski
tagline:          blog
url:              http://sttts.github.io
paginate:         1
baseurl:          /
author:
  name:           Dr. Stefan Schimanski
  url:            https://twitter.com/the1stein
  email:          stefan.schimanski@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/sttts/sttts.github.io

syntax-highlighting:
  enabled : true
  css: syntax.css
